### ISSUE TITLE
Help for creating a new Person record

### ISSUE THREAD

**Issue by antobrita** [BetaMasaheft/Works#417]
Cari,

I'm trying to create a new Person record and, after filling the information required in the fields of the App, I get the following message

![image](https://user-images.githubusercontent.com/19854597/101664536-41280780-3a4c-11eb-8ee5-d8268419134f.png)

I would be very greatful if you can  help me

**Comment by PietroLiuzzo** [comment]
dear Antonella, the file has been successfully created by you today it is here if you need to store it in the repository. https://betamasaheft.eu/persons/PRS13304GabAm.xml

**Comment by antobrita** [comment]
Thank you Pietro!
